### ISSUE TITLE
late/lazy evaluation of colorant" string?

### ISSUE THREAD

**Issue by lobingera** [JuliaGraphics/Colors.jl#262]
```
julia> using Colors

julia> c = colorant"red4"
RGB{U8}(0.545,0.0,0.0)

julia> c
RGB{U8}(0.545,0.0,0.0)

julia> v = v"0.4.1"
v"0.4.1"

julia> v
v"0.4.1"
```

colors are immediately converted from colorant, and so from the moment of conversion on only show up as numbers - while the colorname would be more interesting.
Counterexample is (might be) the version string, which is always displayed as string.

Could a late/lazy evaluation of colorant" be done?

**Comment by timholy** [comment]
Version strings are not really a counterexample, because you can rebuild a string-based representation from version converted to numbers:
```jl
julia> v = v"0.5.1"
v"0.5.1"

julia> dump(v)
VersionNumber
  major: Int64 0
  minor: Int64 5
  patch: Int64 1
  prerelease: Tuple{} ()
  build: Tuple{} ()
```
With colors it's not so obvious how to do that.

If you wanted late evaluation, you could define a type, e.g., `ColorString`, but then you'd also have to write a bunch of functions that accepts them as inputs and converts them to colors when appropriate.

**Comment by lobingera** [comment]
I see.
