### ISSUE TITLE
Working with 2 bytes (16 bits) colors

### ISSUE THREAD

**Issue by scls19fr** [JuliaGraphics/Colors.jl#332]
Hello,

I need to work with RGB colors that are represented as a [2 bytes (16 bits) high color number](https://en.wikipedia.org/wiki/High_color)
with Julia.

Here is a schema for such colors representation
```
1        |1          |        0
5 4 3 2 1|0 9 8 7 6 5|4 3 2 1 0 
---------|-----------|---------
R R R R R|G G G G G G|B B B B B
```

- 5 bits for **red** channel - 32 values

- 6 bis for **green** channel - 64 values (green gets an extra bit because it's the main element of luminance)

- 5 bits for **blue** channel - 32 values

Name|R|G|B|value
----|-|-|-|-----
BLACK|0|0|0|0
WHITE|31|63|31|65535
RED|31|0|0|63488
GREEN|0|63|0|2016
BLUE|0|0|31|31
GRAY|16|33|16|33840
BROWN|23|34|0|48192
YELLOW|31|63|0|65504

I'm not sure how I can use this library with such color representation.

Any idea?

Kind regards

**Comment by scls19fr** [comment]
Same question could also apply to [8-bit_color](https://en.wikipedia.org/wiki/8-bit_color) which are generally represented as

```
7  6  5  4  3  2  1  0
R  R  R  G  G  G  B  B
```

**Comment by AndrewGibb** [comment]
1. Write functions to convert to and from Int or Float based ColorTypes. Use these at the beginning and end of your processing. You probably want to look into compiler intrinsically for the appropriate bit-shifting and masking operations. 

2. Because of how Julia works, you *could* define a new type which describes these colour representations, then re-implement all the functions which are used by the parts of this module with functions specified on your types. However, I’m not sure this approach is same or possible.

**Comment by timholy** [comment]
I would favor @AndrewGibb 's second approach. It shouldn't be that hard; aside from the necessary constructors, the functions you'd have to implement are perhaps just `red`, `green`, and `blue` from [this file](https://github.com/JuliaGraphics/ColorTypes.jl/blob/master/src/traits.jl). Of course it should be a subtype of `AbstractRGB`.

Note this should be done in ColorTypes.jl, not this package.
