### ISSUE TITLE
Dark gray is light

### ISSUE THREAD

**Issue by yha** [JuliaGraphics/Colors.jl#333]
`colorant"darkgray"` is lighter than `colorant"gray"`, which seems odd. It's also much lighter than I'd expect for a "dark" gray. Other dark variants are also a bit inconsistent: "darkblue" is much darker than "blue", but "darkorange" is only slightly darker than "orange".
I suppose it could be reasonable if the names come from some standard palette, but if they do, it doesn't seem to be mentioned in the docs.

**Comment by cormullion** [comment]
Coincidentally I read this earlier this month

>Well basically it boils down to the a bit of legacy awkwardness. The first versions of Mosaic and Netscape Navigator were X Applications, meaning they used the X Windows System on UNIX which defines a set of normalized color names which the browsers pulled in.
Eventually the World Wide Web Consortium (W3C) moved to standardize and merged in the X11 color set, but there were some clashes with what the specification wanted.
In HTML “gray” was reserved for the 128 triplet (as in 50%) gray while X11 defined “gray” as a shade around 75% gray which meant since it was reserved it became a shade of 50% gray throwing away the X11 color value.
On the other hand, “dark-gray” was left alone as it did not exist in HTML or CSS at the time so it was brought in from the X11 definition where it is defined as 66% shade of gray.
As a result, the combined CSS color list that prevails on the web today renders “dark-gray” as a significantly lighter shade than “gray” because “dark-gray” came from X11 while “gray” came from HTML.

If you can think of a suitable place in the docs to mention it, it sounds like a good PR...!
(https://medium.com/commitlog/why-dark-gray-is-brighter-than-gray-on-the-web-cab5b933ec1a)
