### ISSUE TITLE
Tag release with hex parsing support

### ISSUE THREAD

**Issue by MaximeBouton** [JuliaGraphics/Colors.jl#396]
Since it has been implemented and merged in #371 , would it be possible to tag a new release?
Thanks!

**Comment by kimikage** [comment]
Perhaps a new version with the parser extension will be released as Colors v0.12.0 before long.

However, since many packages depend on Colors.jl, frequent minor version upgrades can cause confusion.

At the time of writing, Colors.jl has no PRs scheduled to be merged, including major breaking changes. However, its upstream package ColorTypes.jl will need to introduce breaking changes affecting Colors.jl in the near future (e.g. #273).

As you know, the parsing 6 or 3 digit hex notation without alpha (e.g. "#C0FFEE") is already available.

cc @timholy

**Comment by johnnychen94** [comment]
I prefer to tag every new feature (small or not) as soon as possible to get potential feedbacks from downstream packages if there're no specific maintenance difficulties. (Well, different packages behave differently on this)

**Comment by kimikage** [comment]
I do not object to the rapid release cycles as long as it is version 0. However, I have no control over whether the downstream packages will follow the cycles. I have made maintenance branches in Colors.jl and FixedPointNumbers.jl, but this kind of "rework" does not fit the concept of rapid release cycles. :confused:

Either way, I will "break" ColorTypes.jl in the near future. :stuck_out_tongue:

**Comment by timholy** [comment]
There's definitely a balance to be struck. I don't think it's healthy to accumulate dozens of changes,  without making a release. But I too would prefer to avoid a bunch of busy work.

Just checking, is releasing this new feature breaking? If not, while in the 0.x cycle you can release it as a patch release. That won't require a cascade of upstream compatibility releases.

**Comment by kimikage** [comment]
> Just checking, is releasing this new feature breaking?

I think the answer is unclear. We can consider PR #371 as a pure extension. However, strictly speaking, it is a breaking change, i.e. it breaks the scripts which expect to throw errors for the 4-digit and 8-digit hex notations. What is even more confusing is that the parser of v0.9.6 interprets them as the 3-digit or 6-digit notations (cf. issue #357). :ghost:

Although this is just my preference, I want to release PR #371 and PR #387 as "a set". The latter has clearly breaking changes.

**Comment by timholy** [comment]
Given the potential for parser confusion, sounds like caution is merited.

**Comment by kimikage** [comment]
I’m sorry I kept you waiting, @MaximeBouton. Colors.jl v0.12 with 4-/8-digit hex parsing was released.
