### ISSUE TITLE
[unimportant] Using `sample` with RGB

### ISSUE THREAD

**Issue by anandijain** [JuliaGraphics/Colors.jl#434]
I am interested in sampling random colors without replacement.

Currently using 24bit RGB, and I'm doing this horrible triple loop to generate all colors and then using `StatsBase.sample(;replace=false)`.

Does anyone have a solution to this? 

I'd like to not use `rand` because even though its unlikely that two colors are the same, I don't want to risk it.

**Comment by kimikage** [comment]
What property do you want for pseudo-random numbers (colors)? For example, does the property include cryptographic security?

Shuffling is essentially a bijective map. If you have less requirements, you can easily create such bijective maps with bitwise-shuffling or `xor`.

`UInt32` numbers (in [0, 2^24-1]) can be reinterpreted to `RGB24`.

**Comment by kimikage** [comment]
```julia
using Random

mutable struct XorShift24 <: AbstractRNG
    prev::UInt32
    XorShift24(seed::Integer) = new(seed % 0xFFFFFF + 1) 
end

function Random.rand(rng::XorShift24, ::Random.SamplerType{UInt32}) # The parameters are just an example.  I don't know the randomness.
    x = rng.prev
    x ⊻= x >> 13
    x ⊻= (x << 19) >> 8
    x ⊻= x >> 2
    rng.prev = x
end
```
```julia
julia> r = rand(XorShift24(0), UInt32, 2^24 - 1);

julia> length(unique(r))
16777215

julia> reinterpret(RGB24, rand(XorShift24(1234), UInt32, 2, 2))
2×2 reinterpret(RGB24, ::Array{UInt32,2}):
 RGB24(0.184,0.231,0.906)  RGB24(0.22,0.82,0.58)
 RGB24(0.773,0.22,0.224)   RGB24(0.58,0.816,0.275)
```

**Comment by anandijain** [comment]
Thank you for the great answer!!

I would be using `sample` just to make videos/art, not anything critical, so cryptographic security is overkill (although would be pretty cool). 

I don't have a ton of experience with random number generators, but it looks like your example shows no collisions when I try it, which is the main property I was looking for, and it is much, much faster.

**Comment by kimikage** [comment]
I'm glad I could help you.

When you use the periodical random number sequences for video/art, please note that you may easily consume all `2^24` colors. The seed allows you to change the starting point, but essentially it repeats the same pattern.

Also note that the black `(0, 0, 0)` does not appear in the sequences with period of `2^N-1`, like the Xorshift shown above. This can be resolved by replacing the "absentee" with another color using `xor`, or by inserting a black in the the sequence using `if`-`else`:
```julia
x = rng.prev === 0xC0FFEE ? 0x000000 : rng.prev === 0x000000 ? 0xC0FFEE : rng.prev
```


> Should I close issue?

I've added this "documentation" issue to the ToDo list in #398, so you can close this issue. You can also continue this discussion, because not adding new APIs is a matter of my personal preference. :smile:

**Comment by kimikage** [comment]
We will probably change the implementation of `rand` in ColorTypes.jl in the near future. I'll try to update the documentation based on that.
