### ISSUE TITLE
MethodError: no method matching coloralpha(::Type{RGB24})

### ISSUE THREAD

**Issue by guo-yong-zhi** [JuliaGraphics/Colors.jl#500]
`coloralpha(ARGB(1,1,1,1))` is ok,
but `coloralpha(ARGB32(1,1,1,1))` has error:
>MethodError: no method matching coloralpha(::Type{RGB24})
Closest candidates are:
  coloralpha(::C) where C<:TransparentColor at C:\Users\momos\.julia\packages\ColorTypes\7OlxI\src\conversions.jl:140
  coloralpha(::C, ::Any) where C<:TransparentColor at C:\Users\momos\.julia\packages\ColorTypes\7OlxI\src\conversions.jl:141
  coloralpha(::C) where C<:Color at C:\Users\momos\.julia\packages\ColorTypes\7OlxI\src\conversions.jl:138

**Comment by kimikage** [comment]
This is simply because the type `RGBA32` is not defined in ColorTypes.jl.

You can define it on your own. 
cf. https://github.com/JuliaGraphics/ColorTypes.jl/blob/87364c41644c2fbea5aa7cb049cef15a4afb279f/test/customtypes.jl#L66-L77
However, non-parametric types like `ARGB32` are not well supported in some packages.

As another option, you can submit a PR to add an error hint in ColorTypes.jl.
